import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import SidebarTodo from "@/app/components/SidebarTodo"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			<body className={inter.className}>
				<div className="flex gap-4 mt-12 ">
					<SidebarTodo />
					{children}
				</div>
			</body>
		</html>
  );
}
